# Generated by Django 5.2.3 on 2025-06-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(default='default_book_pic.jpeg', upload_to='books/'),
        ),
    ]
