# Generated by Django 5.2.3 on 2025-06-30 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_starts_given_bookreview_stars_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='default_profile_pic.png', upload_to='authors', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'heic', 'webp'])]),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='book', max_length=250),
            preserve_default=False,
        ),
    ]
